import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
public class Khs extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    /**
     * Creates new form Khs
     */
    public Khs() {
        initComponents();
        koneksi();
        tabel();
        kosong();
    }

        private void koneksi(){
try {
Class.forName("com.mysql.cj.jdbc.Driver");
con=DriverManager.getConnection("jdbc:mysql://localhost/uas_pemrog", "root", "12345678");
stat = con.createStatement();
} catch (ClassNotFoundException | SQLException e) {
JOptionPane.showMessageDialog(null, e);
}
}
    
        private void kosong() {
    txtid.setText(null);
    txtnama.setText(null);
    txtkelas.setText(null);
    txtsemester.setText(null);
    cbmatkul.setSelectedItem(null);
    txthadir.setText(null);
    txttugas.setText(null);
    txtuts.setText(null);
    txtuas.setText(null);
    hnilai.setText(null);
    hgrade.setText(null);
    hstatus.setText(null);
}
   
        private void tabel(){
DefaultTableModel tb= new DefaultTableModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int no=1;
tb.addColumn("No"); 
tb.addColumn("Id"); 
tb.addColumn("Nama");
tb.addColumn("Kelas");
tb.addColumn("Semester");
tb.addColumn("Matkul");
tb.addColumn("Absen");
tb.addColumn("Tugas");
tb.addColumn("UTS");
tb.addColumn("UAS");
tb.addColumn("Nilai");
tb.addColumn("Grade");
tb.addColumn("Status");
jTable1.setModel(tb);
try{
    res=stat.executeQuery("select * from Khs");
    while (res.next())
{
// Mengambil data dari database berdasarkan nama kolom pada tabel
// Lalu di tampilkan ke dalam JTable
tb.addRow(new Object[]
{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12)});

}


}catch (Exception e){
}
}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtkelas = new javax.swing.JTextField();
        txtsemester = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bbaru = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        cbmatkul = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btambah = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bcetak = new javax.swing.JButton();
        txthadir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttugas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtuts = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtuas = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bhitung = new javax.swing.JButton();
        hnilai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hgrade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hstatus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Program Kartu Hasil Studi Mahasiswa");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Kelas");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Semester");

        bbaru.setText("Baru");
        bbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbaruActionPerformed(evt);
            }
        });

        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        cbmatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemrogaman Visual", "Manajemen Sains", "Keamanan Sistem Informasi", "Pemrogaman Berorientasi Objek", "Arsitektur Perusahaan", "Desain Database", "Interaksi Manusia dan Komputer", "Bahasa Inggris 3" }));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Matkul");

        btambah.setText("Tambah");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bcetak.setText("Cetak");
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });

        txthadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthadirActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Kehadiran");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tugas");

        txtuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtutsActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("UTS");

        txtuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuasActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("UAS");

        bhitung.setText("Hitung");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nilai");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Grade");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bhitung)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtuas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(txtuts, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttugas, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                        .addComponent(txtnama))
                                    .addComponent(txtkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtsemester, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbmatkul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txthadir, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(bbaru)
                                        .addGap(18, 18, 18)
                                        .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bcetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(hnilai, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(hgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(22, 22, 22))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbaru)
                    .addComponent(bkeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(bhapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(bcetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(hnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(hgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(hstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(bhitung)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 642, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtutsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtutsActionPerformed

    private void txtuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuasActionPerformed

    private void txthadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthadirActionPerformed

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        // TODO add your handling code here:
        try {
        String query = "SELECT * FROM Khs";
        try (ResultSet resultSet = stat.executeQuery(query)) {
            // Mengumpulkan data dari hasil query
            StringBuilder output = new StringBuilder();
            output.append("<html><body style='text-align:center;'><h1 style='color:red; font-size:24pt;'>Kartu Hasil Studi Mahasiswa</h1><table border='1' style='margin:auto;'>");
            output.append("<tr><th>Id</th><th>Nama</th><th>Kelas</th><th>Semester</th><th>Matkul</th><th>Absen</th><th>Tugas</th><th>UTS</th><th>UAS</th><th>Nilai</th><th>Grade</th><th>Status</th></tr>");

            int no = 1;
            while (resultSet.next()) {
                String id = resultSet.getString("id");
                String nama = resultSet.getString("nama");
                String kelas = resultSet.getString("kelas");
                String semester = resultSet.getString("semester");
                String matkul = resultSet.getString("matkul");
                String hadir = resultSet.getString("hadir");
                String tugas = resultSet.getString("tugas");
                String uts = resultSet.getString("uts");
                String uas = resultSet.getString("uas");
                String nilai = resultSet.getString("nilai");
                String grade = resultSet.getString("grade");
                String status = resultSet.getString("status");

                // Menambahkan data ke StringBuilder dengan format HTML
                output.append("<tr>")
                      .append("<td>").append(id).append("</td>")
                      .append("<td>").append(nama).append("</td>")
                      .append("<td>").append(kelas).append("</td>")
                      .append("<td>").append(semester).append("</td>")
                        .append("<td>").append(matkul).append("</td>")
                        .append("<td>").append(hadir).append("</td>")
                        .append("<td>").append(tugas).append("</td>")
                        .append("<td>").append(uts).append("</td>")
                        .append("<td>").append(uas).append("</td>")
                        .append("<td>").append(nilai).append("</td>")
                        .append("<td>").append(grade).append("</td>")
                        .append("<td>").append(status).append("</td>")
                      .append("</tr>");
            }
            output.append("</table></body></html>");

            // Membuat jendela baru untuk menampilkan data
            JDialog dialog = new JDialog();
            dialog.setTitle("Data Tabel");
            dialog.setSize(600, 500);

            // Membuat JEditorPane untuk menampilkan data HTML
            JEditorPane editorPane = new JEditorPane();
            editorPane.setContentType("text/html");
            editorPane.setText(output.toString());
            editorPane.setEditable(false);

            JScrollPane scrollPane = new JScrollPane(editorPane);
            dialog.add(scrollPane);

            // Menampilkan jendela
            dialog.setVisible(true);
            tabel();
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error fetching and displaying data: " + ex.getMessage());
        ex.printStackTrace();
    }
             
    }//GEN-LAST:event_bcetakActionPerformed

    private void bbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbaruActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_bbaruActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        try {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data?", "Hapus Data", dialogButton);
        if (dialogResult == 0) {
            // Jika pengguna menekan tombol "Yes"
            String idToDelete = txtid.getText();
            String sql = "DELETE FROM khs WHERE id =?";
           
            try (var pst = con.prepareStatement(sql)) {
                pst.setString(1, idToDelete);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                tabel();
                kosong();
            }
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error deleting student: " + ex.getMessage());
        Logger.getLogger(Khs.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bhapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
          String id = jTable1.getValueAt(baris,1).toString();
          txtid.setText(id);
          String nama = jTable1.getValueAt(baris,2).toString();
          txtnama.setText(nama);
          String kelas = jTable1.getValueAt(baris,3).toString();
          txtkelas.setText(kelas);
          String semester = jTable1.getValueAt(baris,4).toString();
          txtsemester.setText(semester);
          String matkul = jTable1.getValueAt(baris,5).toString();
          cbmatkul.setSelectedItem(matkul); 
          String hadir = jTable1.getValueAt(baris,6).toString();
          txthadir.setText(hadir); 
          String tugas = jTable1.getValueAt(baris,7).toString();
          txttugas.setText(tugas); 
          String uts = jTable1.getValueAt(baris,8).toString();
          txtuts.setText(uts);
          String uas = jTable1.getValueAt(baris,9).toString();
          txtuas.setText(uas); 
          String nilai = jTable1.getValueAt(baris,10).toString();
          hnilai.setText(nilai);
          String grade = jTable1.getValueAt(baris,11).toString();
          hgrade.setText(grade); 
          String status = jTable1.getValueAt(baris,12).toString();
          hstatus.setText(status); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
        try {
    String sql = "UPDATE khs SET "
            + "nama=?, id=?, kelas=?, semester=?, matkul=?, hadir=?, tugas=?, uts=?, uas=?, nilai=?, grade=?, status=? WHERE id=?";
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Khs.class.getName()).log(Level.SEVERE, null, ex);
    }

    con = DriverManager.getConnection("jdbc:mysql://localhost/uas_pemrog", "root", "12345678");
    java.sql.PreparedStatement pst = con.prepareStatement(sql);

    // Set parameter values using prepared statement
    pst.setString(1, txtnama.getText());
    pst.setString(2, txtid.getText());
    pst.setString(3, txtkelas.getText());
    pst.setString(4, txtsemester.getText()); 
    pst.setString(5, cbmatkul.getSelectedItem().toString());
    pst.setString(6, txthadir.getText());
    pst.setString(7, txttugas.getText());
    pst.setString(8, txtuts.getText());
    pst.setString(9, txtuas.getText());
    pst.setString(10, hnilai.getText());
    pst.setString(11, hgrade.getText());
    pst.setString(12, hstatus.getText());
    pst.setString(13, txtid.getText()); 

    pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data Berhasil diubah");

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Merubah Data Gagal: " + e.getMessage());
}

tabel();
koneksi();
    }//GEN-LAST:event_beditActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        String id = txtid.getText();
        String nama = txtnama.getText();
        String kelas = txtkelas.getText();
        String semester = txtsemester.getText();
        String matkul = cbmatkul.getSelectedItem().toString();
        
        
        int absen = Integer.parseInt(txthadir.getText());
        int tugas = Integer.parseInt(txttugas.getText());
        int uts = Integer.parseInt(txtuts.getText());
        int uas = Integer.parseInt(txtuas.getText());
        double hsl = (0.1*absen) + (0.4*tugas) + (0.25*uts) + (0.25*uas);
        hnilai.setText(String.valueOf(hsl));
        
        
        //Output dari Program berupa Nilai Akhir, Grade dan Keterangan
        if (hsl >= 80) {
            hgrade.setText("A");
            hstatus.setText("Lulus");
        }
        else if (hsl >= 70) {
            hgrade.setText("B");
            hstatus.setText("Lulus");
        }
        else if (hsl >= 60) {
            hgrade.setText("C");
            hstatus.setText("Mengulang");
        }
        else if (hsl >= 50) {
            hgrade.setText("D");
            hstatus.setText("Mengulang");
        }
        else if (hsl >= 1) {
            hgrade.setText("E");
            hstatus.setText("Mengulang");
        }
        else  {
            hgrade.setText("E");
            hstatus.setText("Mengulang");
        }
    }//GEN-LAST:event_bhitungActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        // TODO add your handling code here:
        try (var pst = con.prepareStatement("insert into khs (id, nama, kelas, semester, matkul, hadir, tugas, uts, uas, nilai, grade, status) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")) {
    // Set values using parameter placeholders
    pst.setString(1, txtid.getText());
    pst.setString(2, txtnama.getText());
    pst.setString(3, txtkelas.getText());
    pst.setString(4, txtsemester.getText());
    pst.setString(5, cbmatkul.getSelectedItem().toString());
    pst.setInt(6, Integer.parseInt(txthadir.getText())); // Convert harga to int
    pst.setInt(7, Integer.parseInt(txttugas.getText())); // Convert jumlah to int
    pst.setInt(8, Integer.parseInt(txtuts.getText()));   // Convert htotal to int
    pst.setInt(9, Integer.parseInt(txtuas.getText()));   // Convert htotal to int
    pst.setString(10, hnilai.getText());
    pst.setString(11, hgrade.getText());
    pst.setString(12, hstatus.getText());

    pst.executeUpdate();
    JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
} catch (SQLException ex) { // Handle SQLException instead of general Exception
    JOptionPane.showMessageDialog(null, "Error adding data: " + ex.getMessage());
    Logger.getLogger(Khs.class.getName()).log(Level.SEVERE, null, ex);
}

tabel();
koneksi();
    }//GEN-LAST:event_btambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Khs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Khs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Khs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Khs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Khs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbaru;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bhitung;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton btambah;
    private javax.swing.JComboBox<String> cbmatkul;
    private javax.swing.JTextField hgrade;
    private javax.swing.JTextField hnilai;
    private javax.swing.JTextField hstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txthadir;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkelas;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtsemester;
    private javax.swing.JTextField txttugas;
    private javax.swing.JTextField txtuas;
    private javax.swing.JTextField txtuts;
    // End of variables declaration//GEN-END:variables
}
